CONFIG_DISK_ACCESS=y
CONFIG_DISK_DRIVER_RAM=y

# File system support
CONFIG_FILE_SYSTEM=y
CONFIG_FAT_FILESYSTEM_ELM=y

# Conflicts with LOG_CMDS, but is required for debug prints
CONFIG_LOG_MODE_MINIMAL=y

CONFIG_EARLY_CONSOLE=y

# Compressing
CONFIG_LZ4=y
CONFIG_LZ4_FRAME_SUPPORT=y
CONFIG_LZ4_XX_HASH=y
CONFIG_DISK_RAM_DECOMPRESS=y

CONFIG_COMMON_LIBC_MALLOC_ARENA_SIZE=163840
